// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OGAS.Data;

#nullable disable

namespace OGAS.Migrations
{
    [DbContext(typeof(OGASDbContext))]
    [Migration("20241207060255_Update")]
    partial class Update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OGAS.Models.产品", b =>
                {
                    b.Property<int>("产品ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("产品ID"));

                    b.Property<string>("产品类别")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("名称")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("描述")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("每单位价格")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("计量单位")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("产品ID");

                    b.ToTable("产品s");
                });

            modelBuilder.Entity("OGAS.Models.产品库存", b =>
                {
                    b.Property<long>("产品库存ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("产品库存ID"));

                    b.Property<int?>("产品ID")
                        .HasColumnType("int");

                    b.Property<string>("产品类型")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("备注")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("数量")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("最后更新时间")
                        .HasColumnType("datetime2");

                    b.Property<string>("计量单位")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("产品库存ID");

                    b.HasIndex("产品ID");

                    b.ToTable("产品库存s");
                });

            modelBuilder.Entity("OGAS.Models.供应商", b =>
                {
                    b.Property<int>("供应商ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("供应商ID"));

                    b.Property<string>("位置")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("名称")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("备注")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("联系信息")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("供应商ID");

                    b.ToTable("供应商s");
                });

            modelBuilder.Entity("OGAS.Models.供应商产品", b =>
                {
                    b.Property<long>("供应商产品ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("供应商产品ID"));

                    b.Property<int>("供应商ID")
                        .HasColumnType("int");

                    b.Property<decimal>("单价")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("材料ID")
                        .HasColumnType("int");

                    b.HasKey("供应商产品ID");

                    b.HasIndex("供应商ID");

                    b.HasIndex("材料ID");

                    b.ToTable("供应商产品s");
                });

            modelBuilder.Entity("OGAS.Models.出口订单", b =>
                {
                    b.Property<long>("订单ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("订单ID"));

                    b.Property<int>("产品ID")
                        .HasColumnType("int");

                    b.Property<decimal>("出口数量")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("收益")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("订单日期")
                        .HasColumnType("datetime2");

                    b.HasKey("订单ID");

                    b.HasIndex("产品ID");

                    b.ToTable("出口订单s");
                });

            modelBuilder.Entity("OGAS.Models.加工厂", b =>
                {
                    b.Property<int>("加工厂ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("加工厂ID"));

                    b.Property<string>("位置")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("加工效率")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("名称")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("状态")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("生产设备ID")
                        .HasColumnType("int");

                    b.Property<string>("联系人信息")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("设备数量")
                        .HasColumnType("int");

                    b.HasKey("加工厂ID");

                    b.HasIndex("生产设备ID");

                    b.ToTable("加工厂s");
                });

            modelBuilder.Entity("OGAS.Models.材料", b =>
                {
                    b.Property<int>("材料ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("材料ID"));

                    b.Property<string>("名称")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("描述")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("材料类别")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("每单位价格")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("计量单位")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("材料ID");

                    b.ToTable("材料s");
                });

            modelBuilder.Entity("OGAS.Models.材料库存", b =>
                {
                    b.Property<long>("材料库存ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("材料库存ID"));

                    b.Property<string>("备注")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("数量")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("最后更新时间")
                        .HasColumnType("datetime2");

                    b.Property<int?>("材料ID")
                        .HasColumnType("int");

                    b.Property<string>("材料类型")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("计量单位")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("材料库存ID");

                    b.HasIndex("材料ID");

                    b.ToTable("材料库存s");
                });

            modelBuilder.Entity("OGAS.Models.生产工艺", b =>
                {
                    b.Property<long>("工艺ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("工艺ID"));

                    b.Property<int>("产品ID")
                        .HasColumnType("int");

                    b.Property<string>("备注")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("安全指引")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("工艺名称")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("材料ID")
                        .HasColumnType("int");

                    b.Property<int>("标准加工时间")
                        .HasColumnType("int");

                    b.Property<int>("生产设备ID")
                        .HasColumnType("int");

                    b.Property<string>("质量标准")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("工艺ID");

                    b.HasIndex("产品ID");

                    b.HasIndex("材料ID");

                    b.HasIndex("生产设备ID");

                    b.ToTable("生产工艺s");
                });

            modelBuilder.Entity("OGAS.Models.生产计划", b =>
                {
                    b.Property<long>("计划ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("计划ID"));

                    b.Property<int>("加工厂ID")
                        .HasColumnType("int");

                    b.Property<string>("备注")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("工艺ID")
                        .HasColumnType("bigint");

                    b.Property<string>("状态")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("计划开始日期")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("计划数量")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("计划类型")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("计划ID");

                    b.HasIndex("加工厂ID");

                    b.HasIndex("工艺ID");

                    b.ToTable("生产计划s");
                });

            modelBuilder.Entity("OGAS.Models.生产记录", b =>
                {
                    b.Property<long>("生产记录ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("生产记录ID"));

                    b.Property<int>("加工厂ID")
                        .HasColumnType("int");

                    b.Property<string>("备注")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("实际开始日期")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("实际结束日期")
                        .HasColumnType("datetime2");

                    b.Property<long>("工艺ID")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("材料成本")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("材料数量")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("材料来源")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("生产数量")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("生产时间")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("生产设备ID")
                        .HasColumnType("int");

                    b.Property<long>("计划ID")
                        .HasColumnType("bigint");

                    b.Property<string>("记录类型")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("质量指标")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("生产记录ID");

                    b.HasIndex("加工厂ID");

                    b.HasIndex("工艺ID");

                    b.HasIndex("生产设备ID");

                    b.HasIndex("计划ID");

                    b.ToTable("生产记录s");
                });

            modelBuilder.Entity("OGAS.Models.生产设备", b =>
                {
                    b.Property<int>("生产设备ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("生产设备ID"));

                    b.Property<string>("名称")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("容量")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("描述")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("效率")
                        .HasColumnType("decimal(3,2)");

                    b.HasKey("生产设备ID");

                    b.ToTable("生产设备s");
                });

            modelBuilder.Entity("OGAS.Models.用户", b =>
                {
                    b.Property<string>("编号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("密码")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("编号");

                    b.ToTable("用户");
                });

            modelBuilder.Entity("OGAS.Models.采购记录", b =>
                {
                    b.Property<int>("采购记录ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("采购记录ID"));

                    b.Property<int>("供应商ID")
                        .HasColumnType("int");

                    b.Property<decimal>("单价")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("总价")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("数量")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("材料ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("采购日期")
                        .HasColumnType("datetime2");

                    b.HasKey("采购记录ID");

                    b.HasIndex("供应商ID");

                    b.HasIndex("材料ID");

                    b.ToTable("采购记录");
                });

            modelBuilder.Entity("OGAS.Models.产品库存", b =>
                {
                    b.HasOne("OGAS.Models.产品", "产品")
                        .WithMany("产品库存s")
                        .HasForeignKey("产品ID");

                    b.Navigation("产品");
                });

            modelBuilder.Entity("OGAS.Models.供应商产品", b =>
                {
                    b.HasOne("OGAS.Models.供应商", "供应商")
                        .WithMany("供应商产品s")
                        .HasForeignKey("供应商ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OGAS.Models.材料", "材料")
                        .WithMany("供应商产品s")
                        .HasForeignKey("材料ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("供应商");

                    b.Navigation("材料");
                });

            modelBuilder.Entity("OGAS.Models.出口订单", b =>
                {
                    b.HasOne("OGAS.Models.产品", "产品")
                        .WithMany("出口订单s")
                        .HasForeignKey("产品ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("产品");
                });

            modelBuilder.Entity("OGAS.Models.加工厂", b =>
                {
                    b.HasOne("OGAS.Models.生产设备", "生产设备")
                        .WithMany("加工厂s")
                        .HasForeignKey("生产设备ID");

                    b.Navigation("生产设备");
                });

            modelBuilder.Entity("OGAS.Models.材料库存", b =>
                {
                    b.HasOne("OGAS.Models.材料", "材料")
                        .WithMany("材料库存s")
                        .HasForeignKey("材料ID");

                    b.Navigation("材料");
                });

            modelBuilder.Entity("OGAS.Models.生产工艺", b =>
                {
                    b.HasOne("OGAS.Models.产品", "产品")
                        .WithMany("生产工艺s")
                        .HasForeignKey("产品ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OGAS.Models.材料", "材料")
                        .WithMany("生产工艺s")
                        .HasForeignKey("材料ID");

                    b.HasOne("OGAS.Models.生产设备", "生产设备")
                        .WithMany("生产工艺s")
                        .HasForeignKey("生产设备ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("产品");

                    b.Navigation("材料");

                    b.Navigation("生产设备");
                });

            modelBuilder.Entity("OGAS.Models.生产计划", b =>
                {
                    b.HasOne("OGAS.Models.加工厂", "加工厂")
                        .WithMany("生产计划s")
                        .HasForeignKey("加工厂ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OGAS.Models.生产工艺", "生产工艺")
                        .WithMany("生产计划s")
                        .HasForeignKey("工艺ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("加工厂");

                    b.Navigation("生产工艺");
                });

            modelBuilder.Entity("OGAS.Models.生产记录", b =>
                {
                    b.HasOne("OGAS.Models.加工厂", "加工厂")
                        .WithMany("生产记录s")
                        .HasForeignKey("加工厂ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OGAS.Models.生产工艺", "生产工艺")
                        .WithMany("生产记录s")
                        .HasForeignKey("工艺ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OGAS.Models.生产设备", "生产设备")
                        .WithMany("生产记录s")
                        .HasForeignKey("生产设备ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OGAS.Models.生产计划", "生产计划")
                        .WithMany("生产记录s")
                        .HasForeignKey("计划ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("加工厂");

                    b.Navigation("生产工艺");

                    b.Navigation("生产计划");

                    b.Navigation("生产设备");
                });

            modelBuilder.Entity("OGAS.Models.采购记录", b =>
                {
                    b.HasOne("OGAS.Models.供应商", "供应商")
                        .WithMany()
                        .HasForeignKey("供应商ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OGAS.Models.材料", "材料")
                        .WithMany()
                        .HasForeignKey("材料ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("供应商");

                    b.Navigation("材料");
                });

            modelBuilder.Entity("OGAS.Models.产品", b =>
                {
                    b.Navigation("产品库存s");

                    b.Navigation("出口订单s");

                    b.Navigation("生产工艺s");
                });

            modelBuilder.Entity("OGAS.Models.供应商", b =>
                {
                    b.Navigation("供应商产品s");
                });

            modelBuilder.Entity("OGAS.Models.加工厂", b =>
                {
                    b.Navigation("生产计划s");

                    b.Navigation("生产记录s");
                });

            modelBuilder.Entity("OGAS.Models.材料", b =>
                {
                    b.Navigation("供应商产品s");

                    b.Navigation("材料库存s");

                    b.Navigation("生产工艺s");
                });

            modelBuilder.Entity("OGAS.Models.生产工艺", b =>
                {
                    b.Navigation("生产计划s");

                    b.Navigation("生产记录s");
                });

            modelBuilder.Entity("OGAS.Models.生产计划", b =>
                {
                    b.Navigation("生产记录s");
                });

            modelBuilder.Entity("OGAS.Models.生产设备", b =>
                {
                    b.Navigation("加工厂s");

                    b.Navigation("生产工艺s");

                    b.Navigation("生产记录s");
                });
#pragma warning restore 612, 618
        }
    }
}
